Insightsreport set corresponding clusteroperator condition correctly
openshift/insights-operator pull request #473
Opened 2021-07-16 12:30 UTC by tremes

This PR registers the `insightsreport` status controller so that the operation can be distinguished and new condition (called `InsightsDownloadDegraded`) introduced 

## Categories

- [X] Bugfix
- [ ] Enhancement
- [ ] Backporting
- [ ] Others (CI, Infrastructure, Documentation)

## Sample Archive

No new data

## Documentation

No doc update

## Unit Tests

I will work on new integration test.

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Changelog

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://bugzilla.redhat.com/show_bug.cgi?id=???
https://access.redhat.com/solutions/???

2021-07-16 12:32 UTC, tremes commented on pkg/controller/status/status.go
> +			klog.V(4).Info("Failed to download Insights report")
I will try to think about some other/better message here....on the other hand it's pretty clear from the previous log messages that the download failed....

2021-07-29 07:01 UTC, rluders requested changes

2021-07-29 07:01 UTC, rluders commented on pkg/insights/insightsreport/insightsreport.go
> +func (r *Controller) Run(ctx context.Context) {
`(c *Controller)`

2021-07-30 10:39 UTC, tremes commented
/retest

2021-08-03 08:34 UTC, rluders commented
/lgtm

2021-08-04 09:31 UTC, merged