DVO metrics gatherer - use UIDs only when DVO deployed in 'openshift-deployment-validation-operator' namespace
openshift/insights-operator pull request #818
Opened 2023-08-14 12:03 UTC by tremes

This is changing the logic for filtering out deployment names, namespace names, etc. to be applied only in case the DVO service is deployed in the `openshift-deployment-validation-operator` namespace.

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

## Documentation

## Unit Tests

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Changelog

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

2023-08-15 05:44 UTC, tremes commented
/retest

2023-08-17 08:44 UTC, ncaak commented
/test insights-operator-e2e-tests

2023-08-17 11:04 UTC, rluders requested changes

2023-08-17 14:14 UTC, ncaak commented
/test e2e-gcp-ovn-techpreview

2023-08-17 16:11 UTC, ncaak commented
/test insights-operator-e2e-tests

2023-08-21 06:33 UTC, tremes commented
/retest

2023-08-21 09:50 UTC, tremes commented on pkg/gatherers/clusterconfig/gather_dvo_metrics.go
> +		if service.Namespace == managedDVONamespaceName {
I think the original approach is more readable, but ok.....

2023-08-21 11:49 UTC, rluders approved these changes
/lgtm

2023-08-21 12:52 UTC, tremes commented
/override ci/prow/e2e-metal-ipi-ovn-ipv6

2023-08-21 12:53 UTC, tremes commented
/retest

2023-08-22 09:39 UTC, tremes commented
/retest

2023-08-22 11:42 UTC, tremes commented
/override ci/prow/e2e-metal-ipi-ovn-ipv6

2023-08-22 12:31 UTC, JoaoFula commented
/retest

2023-08-23 06:07 UTC, merged