NO-JIRA: extend clusteroperators gatherer to collect status of insightsoperato…
openshift/insights-operator pull request #912
Opened 2024-02-22 09:06 UTC by tremes

…r resource

## Categories

- [ ] Bugfix
- [ ] Data Enhancement
- [ ] Feature
- [ ] Backporting
- [X] Others (CI, Infrastructure, Documentation)

## Sample Archive

- `docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/insightsoperator/cluster.json`

## Documentation

- `path/to/documentation.md`

## Unit Tests

## Privacy

Yes. There are no sensitive data in the newly collected information.

## Changelog

## Breaking Changes

No

## References

https://issues.redhat.com/browse/???
https://access.redhat.com/solutions/???

2024-02-22 09:14 UTC, rluders requested changes

2024-02-22 09:14 UTC, rluders commented on pkg/gatherers/clusterconfig/gather_cluster_operators.go
> +		var status interface{}
I would probably change it to:

```go
anonymizeIdentityProviders(clusterResource.Object)
coResource := clusterOperatorResource{
	Spec:       spec,
	Kind:       clusterResource.GetKind(),
	Name:       clusterResource.GetName(),
	APIVersion: clusterResource.GetAPIVersion(),
	namespace:  clusterResource.GetNamespace(),
}

if clusterResource.GetKind() == "InsightsOperator" {
	coResource.Status = clusterResource.Object["status"]
}

res = append(res, coResource)
```

2024-02-26 08:56 UTC, rluders approved these changes
/lgtm

2024-02-26 16:06 UTC, JoaoFula commented
https://gitlab.cee.redhat.com/ccx/insights-operator-tests/-/merge_requests/537

2024-02-26 16:07 UTC, JoaoFula commented
/label qe-approved

2024-02-27 06:48 UTC, tremes commented
/retest

2024-02-28 06:51 UTC, tremes commented
/test insights-operator-e2e-tests

2024-02-29 08:22 UTC, tremes commented
/retest

2024-03-01 06:58 UTC, tremes commented
/test e2e

2024-03-01 09:08 UTC, merged